/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthenticatedBlueprintRouteImport } from './routes/_authenticated/blueprint'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProcessingRouteImport } from './routes/_authenticated/processing'
import { Route as AuthenticatedResourcesRouteImport } from './routes/_authenticated/resources'
import { Route as AuthenticatedResultsRouteImport } from './routes/_authenticated/results'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated/roadmap'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedWelcomeRouteImport } from './routes/_authenticated/welcome'
import { Route as AuthenticatedWizardRouteImport } from './routes/_authenticated/wizard'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedCheckoutSuccessRouteImport } from './routes/_authenticated/checkout.success'
import { Route as AuthenticatedCopilotIndexRouteImport } from './routes/_authenticated/copilot.index'
import { Route as AuthenticatedCopilotPromptsRouteImport } from './routes/_authenticated/copilot.prompts'
import { Route as AuthenticatedCopilotSimulatorRouteImport } from './routes/_authenticated/copilot.simulator'
import { Route as AuthenticatedCopilotChatSessionIdRouteImport } from './routes/_authenticated/copilot.chat.$sessionId'
import { Route as AuthenticatedCopilotDocumentsIndexRouteImport } from './routes/_authenticated/copilot.documents.index'
import { Route as AuthenticatedCopilotDocumentsDocumentIdRouteImport } from './routes/_authenticated/copilot.documents.$documentId'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBlueprintRoute = AuthenticatedBlueprintRouteImport.update({
  id: '/blueprint',
  path: '/blueprint',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProcessingRoute = AuthenticatedProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResourcesRoute = AuthenticatedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResultsRoute = AuthenticatedResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWelcomeRoute = AuthenticatedWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWizardRoute = AuthenticatedWizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCheckoutSuccessRoute =
  AuthenticatedCheckoutSuccessRouteImport.update({
    id: '/checkout/success',
    path: '/checkout/success',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCopilotIndexRoute =
  AuthenticatedCopilotIndexRouteImport.update({
    id: '/copilot/',
    path: '/copilot/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCopilotPromptsRoute =
  AuthenticatedCopilotPromptsRouteImport.update({
    id: '/copilot/prompts',
    path: '/copilot/prompts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCopilotSimulatorRoute =
  AuthenticatedCopilotSimulatorRouteImport.update({
    id: '/copilot/simulator',
    path: '/copilot/simulator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCopilotChatSessionIdRoute =
  AuthenticatedCopilotChatSessionIdRouteImport.update({
    id: '/copilot/chat/$sessionId',
    path: '/copilot/chat/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCopilotDocumentsIndexRoute =
  AuthenticatedCopilotDocumentsIndexRouteImport.update({
    id: '/copilot/documents/',
    path: '/copilot/documents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCopilotDocumentsDocumentIdRoute =
  AuthenticatedCopilotDocumentsDocumentIdRouteImport.update({
    id: '/copilot/documents/$documentId',
    path: '/copilot/documents/$documentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/blueprint': typeof AuthenticatedBlueprintRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/processing': typeof AuthenticatedProcessingRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/results': typeof AuthenticatedResultsRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/wizard': typeof AuthenticatedWizardRoute
  '/api/chat': typeof ApiChatRoute
  '/checkout/success': typeof AuthenticatedCheckoutSuccessRoute
  '/copilot/prompts': typeof AuthenticatedCopilotPromptsRoute
  '/copilot/simulator': typeof AuthenticatedCopilotSimulatorRoute
  '/copilot/': typeof AuthenticatedCopilotIndexRoute
  '/copilot/chat/$sessionId': typeof AuthenticatedCopilotChatSessionIdRoute
  '/copilot/documents/$documentId': typeof AuthenticatedCopilotDocumentsDocumentIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/copilot/documents/': typeof AuthenticatedCopilotDocumentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/blueprint': typeof AuthenticatedBlueprintRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/processing': typeof AuthenticatedProcessingRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/results': typeof AuthenticatedResultsRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/wizard': typeof AuthenticatedWizardRoute
  '/api/chat': typeof ApiChatRoute
  '/checkout/success': typeof AuthenticatedCheckoutSuccessRoute
  '/copilot/prompts': typeof AuthenticatedCopilotPromptsRoute
  '/copilot/simulator': typeof AuthenticatedCopilotSimulatorRoute
  '/copilot': typeof AuthenticatedCopilotIndexRoute
  '/copilot/chat/$sessionId': typeof AuthenticatedCopilotChatSessionIdRoute
  '/copilot/documents/$documentId': typeof AuthenticatedCopilotDocumentsDocumentIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/copilot/documents': typeof AuthenticatedCopilotDocumentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/_authenticated/blueprint': typeof AuthenticatedBlueprintRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/processing': typeof AuthenticatedProcessingRoute
  '/_authenticated/resources': typeof AuthenticatedResourcesRoute
  '/_authenticated/results': typeof AuthenticatedResultsRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/welcome': typeof AuthenticatedWelcomeRoute
  '/_authenticated/wizard': typeof AuthenticatedWizardRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/checkout/success': typeof AuthenticatedCheckoutSuccessRoute
  '/_authenticated/copilot/prompts': typeof AuthenticatedCopilotPromptsRoute
  '/_authenticated/copilot/simulator': typeof AuthenticatedCopilotSimulatorRoute
  '/_authenticated/copilot/': typeof AuthenticatedCopilotIndexRoute
  '/_authenticated/copilot/chat/$sessionId': typeof AuthenticatedCopilotChatSessionIdRoute
  '/_authenticated/copilot/documents/$documentId': typeof AuthenticatedCopilotDocumentsDocumentIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/_authenticated/copilot/documents/': typeof AuthenticatedCopilotDocumentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pricing'
    | '/blueprint'
    | '/dashboard'
    | '/processing'
    | '/resources'
    | '/results'
    | '/roadmap'
    | '/settings'
    | '/welcome'
    | '/wizard'
    | '/api/chat'
    | '/checkout/success'
    | '/copilot/prompts'
    | '/copilot/simulator'
    | '/copilot/'
    | '/copilot/chat/$sessionId'
    | '/copilot/documents/$documentId'
    | '/api/public/payments/webhook'
    | '/copilot/documents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pricing'
    | '/blueprint'
    | '/dashboard'
    | '/processing'
    | '/resources'
    | '/results'
    | '/roadmap'
    | '/settings'
    | '/welcome'
    | '/wizard'
    | '/api/chat'
    | '/checkout/success'
    | '/copilot/prompts'
    | '/copilot/simulator'
    | '/copilot'
    | '/copilot/chat/$sessionId'
    | '/copilot/documents/$documentId'
    | '/api/public/payments/webhook'
    | '/copilot/documents'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/pricing'
    | '/_authenticated/blueprint'
    | '/_authenticated/dashboard'
    | '/_authenticated/processing'
    | '/_authenticated/resources'
    | '/_authenticated/results'
    | '/_authenticated/roadmap'
    | '/_authenticated/settings'
    | '/_authenticated/welcome'
    | '/_authenticated/wizard'
    | '/api/chat'
    | '/_authenticated/checkout/success'
    | '/_authenticated/copilot/prompts'
    | '/_authenticated/copilot/simulator'
    | '/_authenticated/copilot/'
    | '/_authenticated/copilot/chat/$sessionId'
    | '/_authenticated/copilot/documents/$documentId'
    | '/api/public/payments/webhook'
    | '/_authenticated/copilot/documents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PricingRoute: typeof PricingRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/blueprint': {
      id: '/_authenticated/blueprint'
      path: '/blueprint'
      fullPath: '/blueprint'
      preLoaderRoute: typeof AuthenticatedBlueprintRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/processing': {
      id: '/_authenticated/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof AuthenticatedProcessingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resources': {
      id: '/_authenticated/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthenticatedResourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results': {
      id: '/_authenticated/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AuthenticatedResultsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/welcome': {
      id: '/_authenticated/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthenticatedWelcomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wizard': {
      id: '/_authenticated/wizard'
      path: '/wizard'
      fullPath: '/wizard'
      preLoaderRoute: typeof AuthenticatedWizardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/checkout/success': {
      id: '/_authenticated/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof AuthenticatedCheckoutSuccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/copilot/': {
      id: '/_authenticated/copilot/'
      path: '/copilot'
      fullPath: '/copilot/'
      preLoaderRoute: typeof AuthenticatedCopilotIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/copilot/prompts': {
      id: '/_authenticated/copilot/prompts'
      path: '/copilot/prompts'
      fullPath: '/copilot/prompts'
      preLoaderRoute: typeof AuthenticatedCopilotPromptsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/copilot/simulator': {
      id: '/_authenticated/copilot/simulator'
      path: '/copilot/simulator'
      fullPath: '/copilot/simulator'
      preLoaderRoute: typeof AuthenticatedCopilotSimulatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/copilot/chat/$sessionId': {
      id: '/_authenticated/copilot/chat/$sessionId'
      path: '/copilot/chat/$sessionId'
      fullPath: '/copilot/chat/$sessionId'
      preLoaderRoute: typeof AuthenticatedCopilotChatSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/copilot/documents/': {
      id: '/_authenticated/copilot/documents/'
      path: '/copilot/documents'
      fullPath: '/copilot/documents/'
      preLoaderRoute: typeof AuthenticatedCopilotDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/copilot/documents/$documentId': {
      id: '/_authenticated/copilot/documents/$documentId'
      path: '/copilot/documents/$documentId'
      fullPath: '/copilot/documents/$documentId'
      preLoaderRoute: typeof AuthenticatedCopilotDocumentsDocumentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBlueprintRoute: typeof AuthenticatedBlueprintRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProcessingRoute: typeof AuthenticatedProcessingRoute
  AuthenticatedResourcesRoute: typeof AuthenticatedResourcesRoute
  AuthenticatedResultsRoute: typeof AuthenticatedResultsRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWelcomeRoute: typeof AuthenticatedWelcomeRoute
  AuthenticatedWizardRoute: typeof AuthenticatedWizardRoute
  AuthenticatedCheckoutSuccessRoute: typeof AuthenticatedCheckoutSuccessRoute
  AuthenticatedCopilotPromptsRoute: typeof AuthenticatedCopilotPromptsRoute
  AuthenticatedCopilotSimulatorRoute: typeof AuthenticatedCopilotSimulatorRoute
  AuthenticatedCopilotIndexRoute: typeof AuthenticatedCopilotIndexRoute
  AuthenticatedCopilotChatSessionIdRoute: typeof AuthenticatedCopilotChatSessionIdRoute
  AuthenticatedCopilotDocumentsDocumentIdRoute: typeof AuthenticatedCopilotDocumentsDocumentIdRoute
  AuthenticatedCopilotDocumentsIndexRoute: typeof AuthenticatedCopilotDocumentsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBlueprintRoute: AuthenticatedBlueprintRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProcessingRoute: AuthenticatedProcessingRoute,
  AuthenticatedResourcesRoute: AuthenticatedResourcesRoute,
  AuthenticatedResultsRoute: AuthenticatedResultsRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWelcomeRoute: AuthenticatedWelcomeRoute,
  AuthenticatedWizardRoute: AuthenticatedWizardRoute,
  AuthenticatedCheckoutSuccessRoute: AuthenticatedCheckoutSuccessRoute,
  AuthenticatedCopilotPromptsRoute: AuthenticatedCopilotPromptsRoute,
  AuthenticatedCopilotSimulatorRoute: AuthenticatedCopilotSimulatorRoute,
  AuthenticatedCopilotIndexRoute: AuthenticatedCopilotIndexRoute,
  AuthenticatedCopilotChatSessionIdRoute:
    AuthenticatedCopilotChatSessionIdRoute,
  AuthenticatedCopilotDocumentsDocumentIdRoute:
    AuthenticatedCopilotDocumentsDocumentIdRoute,
  AuthenticatedCopilotDocumentsIndexRoute:
    AuthenticatedCopilotDocumentsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PricingRoute: PricingRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
